# Generated by Django 5.0.6 on 2025-07-23 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=255, unique=True)),
                ('playlist_url', models.URLField(unique=True)),
                ('playlist_name', models.CharField(max_length=255)),
                ('playlist_owner', models.CharField(max_length=255)),
                ('playlist_image', models.URLField(blank=True, null=True)),
                ('playlist_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=255)),
                ('track_name', models.CharField(max_length=255)),
                ('track_duration_ms', models.IntegerField()),
                ('track_popularity', models.IntegerField(blank=True, null=True)),
                ('track_genres', models.JSONField(default=list)),
                ('album_id', models.CharField(max_length=255)),
                ('album_name', models.CharField(max_length=255)),
                ('album_release_date', models.DateField(blank=True, null=True)),
                ('album_label', models.CharField(blank=True, max_length=255, null=True)),
                ('artist_ids', models.JSONField(default=list)),
                ('artist_names', models.JSONField(default=list)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='dashboard.playlist')),
            ],
        ),
    ]
