# Generated by Django 5.2.3 on 2025-07-30 03:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_url',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('user', 'playlist_id')},
        ),
    ]
