# Generated by Django 5.2.3 on 2025-07-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_playlist_playlist_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_id',
            field=models.CharField(max_length=255),
        ),
    ]
