# Generated by Django 5.0.6 on 2025-12-30 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_playlist_playlist_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('playlist', 'track_id')},
        ),
    ]
